export interface IAutogeneratedRoutineExercise {
    nombre: string;
    series: number;
    repeticiones: string;
    comentario: string;
    id_ejercicio: number;
    orden: number;
    tipo: string;
    step_1: string;
    step_2: string;
    grupos_musculares: string;
}

export interface IAutogeneratedRoutine {
    rutina_id: number;
    nombre: string;
    rutina_observaciones: string;
    realizada: number;
    metodo: string;
    objetivo: string;
    dificultad: string;
    tiempo_aerobicos: string;
    tiempo_anaerobicos: string;
    metodo_observaciones: string;
    descanso: string;
    objetivos_id: number;
    dificultad_id: number;
    metodos_id: number;
    dia: string;
    ejercicios: IAutogeneratedRoutineExercise[];
}